// export class booksData {
export const booksData = [
  // BooksArray = [
  {
    id: '1',
    titre: 'math',
    auteur: 'colby convigton',
    category: 'science',
    published_date: '10/5/1998',
    reviews: 1997,
    stars: '3,5 ⭐',
    nbre_page: 20,
    prix: '5 $',
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51n382CyioL._SX218_BO1,204,203,200_QL40_FMwebp_.jpg',
    goals: [
      'Understand how computers work from inside out',
      'Understand basic concepts of software programming (in Java, Python, PHP)',
      'Fundamentals of databases, mobile apps and cloud computing',
      'Write basic software programs and applications',
    ],
    requirements: [
      'No technical prerequisites for this course.',
      "I assume that you have used a computer and/or smartphones before, but I don't expect you to have any other technical knowledge.",
    ],
  },
  {
    id: '2',
    titre: 'Poor economics',
    auteur: 'kumaru usman',
    prix: '500 $',
    reviews: 8228,
    stars: '⭐⭐⭐⭐',
    category: 'science',
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/41hV+q2UlkL._SY344_BO1,204,203,200_.jpg',
    published_date: '10/11/2005',
    nbre_page: 50,
    goals: [
      'Understand how computers work from inside out',
      'Understand basic concepts of software programming (in Java, Python, PHP)',
      'Fundamentals of databases, mobile apps and cloud computing',
      'Write basic software programs and applications',
    ],
    requirements: [
      'No technical prerequisites for this course.',
      "I assume that you have used a computer and/or smartphones before, but I don't expect you to have any other technical knowledge.",
    ],
  },
  {
    id: '3',
    titre: 'Pure Physique',
    auteur: 'Michael Lipowski',
    prix: '300 £',
    reviews: 8228,
    stars: '⭐⭐⭐⭐',
    category: 'sport',
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/41UCrRU88SL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
    published_date: '10/11/2008',
    nbre_page: 20,
    goals: [
      'Understand how computers work from inside out',
      'Understand basic concepts of software programming (in Java, Python, PHP)',
      'Fundamentals of databases, mobile apps and cloud computing',
      'Write basic software programs and applications',
    ],
    requirements: [
      'No technical prerequisites for this course.',
      "I assume that you have used a computer and/or smartphones before, but I don't expect you to have any other technical knowledge.",
    ],
  },
  {
    id: 4,
    titre: 'Predictably Irrational',
    auteur: 'Dr. dan ariely',
    prix: '300 $',
    reviews: 8228,
    stars: '⭐⭐',
    category: 'economics',
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/516XdxUXpNL._SX326_BO1,204,203,200_.jpg',
    published_date: '10/11/1997',
    nbre_page: 50,
    goals: [
      'Understand how computers work from inside out',
      'Understand basic concepts of software programming (in Java, Python, PHP)',
      'Fundamentals of databases, mobile apps and cloud computing',
      'Write basic software programs and applications',
    ],
    requirements: [
      'No technical prerequisites for this course.',
      "I assume that you have used a computer and/or smartphones before, but I don't expect you to have any other technical knowledge.",
    ],
  },
  {
    id: 5,
    titre: 'The Storyteller: Tales of Life and Music',
    auteur: 'Drave Grohl',
    prix: '26.94 $',
    reviews: 8228,
    stars: '4,5 ⭐',
    category: 'Audio Book',
    imageUrl: 'https://m.media-amazon.com/images/I/51PsdEs6H9S.jpg',
    published_date: '10/11/2020',
    nbre_page: 50,
    goals: [
      'Understand how computers work from inside out',
      'Understand basic concepts of software programming (in Java, Python, PHP)',
      'Fundamentals of databases, mobile apps and cloud computing',
      'Write basic software programs and applications',
    ],
    requirements: [
      'No technical prerequisites for this course.',
      "I assume that you have used a computer and/or smartphones before, but I don't expect you to have any other technical knowledge.",
    ],
  },
  {
    id: 6,
    titre: 'Geopolitics of blood',
    auteur: 'Safi Said',
    prix: '20 $',
    reviews: 8228,
    stars: '⭐⭐⭐⭐⭐',
    category: 'politics',
    imageUrl: 'https://m.media-amazon.com/images/I/41Y9jM-Le2L.jpg',
    published_date: '10/11/2020',
    nbre_page: 50,
    goals: [
      'Understand how computers work from inside out',
      'Understand basic concepts of software programming (in Java, Python, PHP)',
      'Fundamentals of databases, mobile apps and cloud computing',
      'Write basic software programs and applications',
    ],
    requirements: [
      'No technical prerequisites for this course.',
      "I assume that you have used a computer and/or smartphones before, but I don't expect you to have any other technical knowledge.",
    ],
  },
  {
    id: 7,
    titre: 'The judge s List: A Novel',
    auteur: 'elon musk',
    prix: '30.94 $',
    reviews: 8228,
    stars: '⭐⭐⭐',
    category: 'Biography',
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/71N7vj5cSkL._AC_UL210_SR195,210_.jpg',
    published_date: '10/9/2021',
    nbre_page: 50,
    goals: [
      'Understand how computers work from inside out',
      'Understand basic concepts of software programming (in Java, Python, PHP)',
      'Fundamentals of databases, mobile apps and cloud computing',
      'Write basic software programs and applications',
    ],
    requirements: [
      'No technical prerequisites for this course.',
      "I assume that you have used a computer and/or smartphones before, but I don't expect you to have any other technical knowledge.",
    ],
  },
  {
    id: 8,
    titre: 'Ace the Data Science Interview',
    auteur: 'Drave Grohl',
    prix: '30.94 $',
    reviews: 8228,
    stars: '⭐⭐⭐⭐⭐',
    category: 'Science',
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/41A3imtffCL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
    published_date: '10/12/2019',
    nbre_page: 25,
    goals: [
      'Understand how computers work from inside out',
      'Understand basic concepts of software programming (in Java, Python, PHP)',
      'Fundamentals of databases, mobile apps and cloud computing',
      'Write basic software programs and applications',
    ],
    requirements: [
      'No technical prerequisites for this course.',
      "I assume that you have used a computer and/or smartphones before, but I don't expect you to have any other technical knowledge.",
    ],
  },
  {
    id: 9,
    titre: 'Deep Learning',
    auteur: 'Drave Grohl',
    prix: '30.94 $',
    reviews: 4802,
    stars: '4,5 🌟',
    category: 'Science',
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/61qbj4KwauL._SX218_BO1,204,203,200_QL40_FMwebp_.jpg',
    published_date: '10/12/2019',
    nbre_page: 47,
    goals: [
      'Understand how computers work from inside out',
      'Understand basic concepts of software programming (in Java, Python, PHP)',
      'Fundamentals of databases, mobile apps and cloud computing',
      'Write basic software programs and applications',
    ],
    requirements: [
      'No technical prerequisites for this course.',
      "I assume that you have used a computer and/or smartphones before, but I don't expect you to have any other technical knowledge.",
    ],
  },
  {
    id: 10,
    titre: 'The Complete book of angular 6',
    auteur: 'Nathan Murray',
    prix: '59.5 $',
    reviews: 4802,
    stars: '🌟🌟🌟',
    // 🌟
    category: 'Software framework',
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/5189dK2traL._SX384_BO1,204,203,200_.jpg',
    published_date: '09/11/2020',
    nbre_page: 50,
    goals: [
      'Understand how computers work from inside out',
      'Understand basic concepts of software programming (in Java, Python, PHP)',
      'Fundamentals of databases, mobile apps and cloud computing',
      'Write basic software programs and applications',
    ],
    requirements: [
      'No technical prerequisites for this course.',
      "I assume that you have used a computer and/or smartphones before, but I don't expect you to have any other technical knowledge.",
    ],
  },
  {
    id: 11,
    titre: 'React.js Book: Learning React JavaScript Library From Scratch',
    auteur: 'Greg Sidelnikov',
    prix: '59.5 $',
    reviews: 4802,
    stars: '4,5 ⭐',
    category: 'Software framework',
    imageUrl: 'https://m.media-amazon.com/images/I/51BXdIhEe1L._SX260_.jpg',
    published_date: '09/11/2020',
    nbre_page: 60,
    goals: [
      'Understand how computers work from inside out',
      'Understand basic concepts of software programming (in Java, Python, PHP)',
      'Fundamentals of databases, mobile apps and cloud computing',
      'Write basic software programs and applications',
    ],
    requirements: [
      'No technical prerequisites for this course.',
      "I assume that you have used a computer and/or smartphones before, but I don't expect you to have any other technical knowledge.",
    ],
  },
  {
    id: 12,
    titre: 'Node Cookbook',
    auteur: 'Bethany Griggs',
    prix: '15.24 $',
    reviews: 4802,
    stars: '⭐⭐⭐⭐',
    category: 'Software framework',
    imageUrl:
      'https://images-na.ssl-images-amazon.com/images/I/51tPFqRdrjL._SY445_SX342_QL70_FMwebp_.jpg',
    published_date: '09/11/2021',
    nbre_page: 40,
    goals: [
      'Understand how computers work from inside out',
      'Understand basic concepts of software programming (in Java, Python, PHP)',
      'Fundamentals of databases, mobile apps and cloud computing',
      'Write basic software programs and applications',
    ],
    requirements: [
      'No technical prerequisites for this course.',
      "I assume that you have used a computer and/or smartphones before, but I don't expect you to have any other technical knowledge.",
    ],
  },
];
